title = "CCHS Instrumental Music"
baseURL = "https://ccinstrumental.org"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "ccinstrumental"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "CCHS INSTRUMENTAL MUSIC"
  author = "Christopher Noce"
  description = "Concord-Carlisle High School Bands & Orchestra"
  logoBig = "/images/ccinstrumental_logo.png"
  logoSmall = "/images/ccinstrumental_logo.png"
  favicon = "favicon.ico"
  opengraphImage = "/images/ccinstrumental_logo.png"
  email = "cnoce@concordcarlisle.org"
  googleTagManger = ""
  customCSS = false

  # Social media links in footer
  twitter = "ccinstrumental"
  instagram = "cc.instrumental"
  facebook = "cchsinstrumental"

  # Copyright and theme author credit in footer
  copyright = true
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = false
  ajaxFormspreeGold = false
  ajaxBasin = false

  # Lazy loading with lazysizes
  lazyloading = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Calendar"
  url  = "/#calendar"
  weight = 2
[[menu.main]]
  name = "News"
  url  = "/#news"
  weight = 3